tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/fuse'
tap 'homebrew/science'
tap 'homebrew/versions'
cask 'java'
cask 'osxfuse'
cask 'xquartz'
brew 'ant'
brew 'autoconf'
brew 'xz'
brew 'automake'
brew 'awscli'
brew 'bash-completion'
brew 'pkg-config'
brew 'libpng', args: ['universal']
brew 'freetype', args: ['universal']
brew 'fontconfig', args: ['universal']
brew 'pixman'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'cairo'
brew 'cmake'
brew 'gmp'
brew 'coreutils'
brew 'git'
brew 'docker'
brew 'jpeg', args: ['universal']
brew 'libtiff', args: ['universal']
brew 'little-cms2', args: ['universal']
brew 'ghostscript'
brew 'epstool'
brew 'exercism'
brew 'faac'
brew 'mpfr'
brew 'libmpc'
brew 'isl'
brew 'gcc'
brew 'fftw'
brew 'findutils'
brew 'fswatch'
brew 'gd', args: ['universal']
brew 'gdbm'
brew 'gl2ps'
brew 'gnu-sed'
brew 'gnupg'
brew 'lua'
brew 'readline'
brew 'makedepend'
brew 'openssl', args: ['universal']
brew 'mysql'
brew 'icu4c'
brew 'sqlite'
brew 'python'
brew 'postgresql'
brew 'qt'
brew 'gnuplot', args: ['with-aquaterm']
brew 'libtasn1', args: ['universal']
brew 'nettle'
brew 'gnutls'
brew 'gobject-introspection'
brew 'libtool', args: ['universal']
brew 'jasper', args: ['universal']
brew 'graphicsmagick'
brew 'harfbuzz'
brew 'pango'
brew 'graphviz'
brew 'htop-osx'
brew 'imagemagick'
brew 'irssi'
brew 'oniguruma'
brew 'jq'
brew 'lame'
brew 'x264'
brew 'xvid'
brew 'libav'
brew 'libevent'
brew 'libgpg-error'
brew 'libusb', args: ['universal']
brew 'libusb-compat', args: ['universal']
brew 'libgphoto2', args: ['universal']
brew 'libicns', args: ['universal']
brew 'libksba'
brew 'libssh2'
brew 'libxml2'
brew 'libyaml'
brew 'maven'
brew 'mercurial'
brew 'protobuf'
brew 'mitmproxy'
brew 'moreutils'
brew 'multirust'
brew 'nasm'
brew 'nmap'
brew 'node'
brew 'plotutils'
brew 'pstoedit'
brew 'sip'
brew 'pyqt'
brew 'qscintilla2'
brew 'ruby-build'
brew 'rbenv'
brew 'redis'
brew 'sane-backends', args: ['universal']
brew 'sbt'
brew 'scala'
brew 'szip'
brew 'tbb'
brew 'texinfo'
brew 'tmux'
brew 'tree'
brew 'typesafe-activator'
brew 'watch'
brew 'wget'
brew 'wine'
brew 'homebrew/fuse/sshfs'
brew 'homebrew/science/veclibfort'
brew 'homebrew/science/arpack'
brew 'homebrew/science/glpk'
brew 'homebrew/science/hdf5'
brew 'homebrew/science/h5utils'
brew 'homebrew/science/metis'
brew 'homebrew/science/qhull'
brew 'homebrew/science/qrupdate'
brew 'homebrew/science/suite-sparse'
brew 'homebrew/science/octave'
brew 'homebrew/science/suite-sparse421'
brew 'homebrew/versions/postgresql94'
cask '1password'
cask 'android-file-transfer'
cask 'angband'
cask 'arduino'
cask 'battle-net'
cask 'dropbox'
cask 'flux'
cask 'google-chrome'
cask 'google-photos-backup'
cask 'intellij-idea-ce'
cask 'iterm2-beta'
cask 'menumeters'
cask 'moom'
cask 'openoffice'
cask 'postico'
cask 'serviio'
cask 'skype'
cask 'slack'
cask 'sourcetree'
cask 'spotify'
cask 'steam'
cask 'sublime-text-dev'
cask 'telegram'
cask 'thunderbird'
cask 'transmission'
cask 'vlc'
cask 'whatsapp'
cask 'xmind'
